[package]
name = "lcpgn"
version = "0.1.0"
authors = ["Yan Zhang <cyanogenoid@cyanogenoid.com>"]
edition = "2018"

[dependencies]
chess = "3.0"
pgn-reader = "0.13"
flatbuffers = "0.5"
structopt = "0.2"

[build-dependencies]
flatc-rust = "*"
